### ISSUE TITLE
Dead link in Scope.md document

### ISSUE THREAD

**Issue by goneall** [CommunitySpecification/Community_Specification#1]
The link https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/how-to-write-standards.pdf in the [scope.md](https://github.com/CommunitySpecification/1.0/blob/master/2._Scope.md) file return an HTTP 404 (document not found).

**Comment by mkdolan** [comment]
Thanks @goneall - we've addressed this in the development branch.
